import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated Prisma client (regenerated by every build; not hand-edited code):
    "src/generated/**",
    // tsup worker bundle (04-01): generated CJS output of src/worker/** —
    // its require() calls are the point of the format (D-03), not lintable
    // source. Same posture as src/generated.
    "dist/**",
  ]),
]);

export default eslintConfig;
