import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated Prisma client (regenerated by every build; not hand-edited code):
    "src/generated/**",
    // tsup worker bundle (04-01): generated CJS output of src/worker/** —
    // its require() calls are the point of the format (D-03), not lintable
    // source. Same posture as src/generated.
    "dist/**",
    // Foreign-tool workspaces nested in the repo root (05-09 Rule-3 unblock):
    // .kilo/worktrees/* are linked git worktrees another agent IDE creates
    // inside the project — stale branch checkouts, never this repo's source
    // of truth. Same posture as .next/dist: tool-owned, not lintable.
    ".kilo/**",
    // Agent-runtime tooling installed under the repo root (07-08 Rule-3
    // unblock): the GSD/agent harnesses' vendored .cjs/.mjs bundles and
    // per-tool workspaces are tool-owned generated content left untracked by
    // project convention — 15k+ no-require-imports errors over code this
    // repo never ships. Same posture as .kilo above.
    ".agents/**",
    ".augment/**",
    ".claude/**",
    ".clinerules/**",
    ".codebuddy/**",
    ".codex/**",
    ".cursor/**",
    ".github/**",
    ".hermes/**",
    ".kilo/**",
    ".opencode/**",
    ".pi/**",
    ".qwen/**",
    ".trae/**",
    ".windsurf/**",
    ".zcode/**",
    "agents/**",
    "gsd-core/**",
    "gsd-file-manifest.json",
    "gsd-install-state.json",
    "scripts/changeset/**",
    "scripts/fix-slash-commands.cjs",
    "scripts/gen-capability-registry.cjs",
    "scripts/gen-loop-host-contract.cjs",
    "scripts/lib/**",
  ]),
]);

export default eslintConfig;
