// SpiderNode schema — the single Drizzle schema authority (D-07).
//
// PROVENANCE (DRZ-01): generated by `drizzle-kit pull` (schemaFilter public)
// from a LIVE production snapshot restored into a throwaway container
// (03-03 Task 2), then hand-finished line-by-line against
// .snapshots/prod-schema-only.sql and docs/ARCHITECTURE-AUDIT.md §11.
// NEVER derived from prisma/schema.prisma (frozen, D-09) — the live DDL is
// the only source of truth for existing objects (M-6 drift rule).
//
// GATE CONTRACT (03-07, D-13): the code below keeps the exact formatting
// drizzle-kit pull emits (single quotes, no semicolons, pull's column
// ordering). The empty-diff gate diffs this file against a normalized pull
// of a migrated database — cosmetic reformatting here would break the gate.
// Only comments (stripped by the gate's normalization) may differ.
//
// NOT HERE: the audit §11 worker prerequisites (claim column + due index,
// guards table, alert event table, failure-count column, ping check-metadata
// columns, the one-ongoing partial unique index). They are absent from
// production today and arrive as migration 0001 in 03-04.
//
// Live-DDL facts recorded at pull time (03-03): source PostgreSQL 17
// (local spidernode-dev-db container — no Neon involved); every time column
// is `timestamp(3) without time zone` (A6 drift confirmed — naive, not
// timestamptz); text PKs carry NO database default (app-side cuid today;
// gen_random_uuid()::text defaults arrive with migration 0001 per §11);
// `_prisma_migrations` is ABSENT (A4 — schema was db-push'd, never
// migrate-deploy'd; 03-07's gate needs no tablesFilter exclusion).
import { pgTable, index, foreignKey, text, integer, timestamp, serial, boolean, doublePrecision, uniqueIndex } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const feedbacks = pgTable("feedbacks", {
	id: text().primaryKey().notNull(),
	userId: text().notNull(),
	type: text().notNull(),
	title: text().notNull(),
	description: text().notNull(),
	status: text().default('PENDING').notNull(),
	upvotes: integer().default(0).notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	index("feedbacks_userId_idx").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "feedbacks_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const monitors = pgTable("monitors", {
	id: serial().primaryKey().notNull(),
	url: text().notNull(),
	name: text().notNull(),
	status: text().default('UNKNOWN').notNull(),
	isActive: boolean().default(true).notNull(),
	interval: integer().default(5).notNull(),
	lastChecked: timestamp({ precision: 3, mode: 'string' }),
	responseTime: integer().default(0),
	uptimePercent: doublePrecision().default(100).notNull(),
	totalChecks: integer().default(0).notNull(),
	failedChecks: integer().default(0).notNull(),
	userId: text().notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "monitors_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const pings = pgTable("pings", {
	id: text().primaryKey().notNull(),
	monitorId: integer().notNull(),
	status: text().notNull(),
	responseTime: integer().notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	index("pings_monitorId_idx").using("btree", table.monitorId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.monitorId],
			foreignColumns: [monitors.id],
			name: "pings_monitorId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const sessions = pgTable("sessions", {
	id: text().primaryKey().notNull(),
	sessionToken: text().notNull(),
	userId: text().notNull(),
	expires: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("sessions_sessionToken_key").using("btree", table.sessionToken.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "sessions_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const passwordResetTokens = pgTable("password_reset_tokens", {
	id: text().primaryKey().notNull(),
	email: text().notNull(),
	token: text().notNull(),
	expires: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("password_reset_tokens_email_token_key").using("btree", table.email.asc().nullsLast().op("text_ops"), table.token.asc().nullsLast().op("text_ops")),
	uniqueIndex("password_reset_tokens_token_key").using("btree", table.token.asc().nullsLast().op("text_ops")),
]);

export const incidents = pgTable("incidents", {
	id: text().primaryKey().notNull(),
	monitorId: integer().notNull(),
	status: text().notNull(),
	description: text(),
	startedAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	resolvedAt: timestamp({ precision: 3, mode: 'string' }),
}, (table) => [
	index("incidents_monitorId_idx").using("btree", table.monitorId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.monitorId],
			foreignColumns: [monitors.id],
			name: "incidents_monitorId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const verificationTokens = pgTable("verification_tokens", {
	id: text().primaryKey().notNull(),
	email: text().notNull(),
	token: text().notNull(),
	expires: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("verification_tokens_email_token_key").using("btree", table.email.asc().nullsLast().op("text_ops"), table.token.asc().nullsLast().op("text_ops")),
	uniqueIndex("verification_tokens_token_key").using("btree", table.token.asc().nullsLast().op("text_ops")),
]);

export const users = pgTable("users", {
	id: text().primaryKey().notNull(),
	name: text(),
	email: text().notNull(),
	emailVerified: timestamp({ precision: 3, mode: 'string' }),
	image: text(),
	password: text(),
	telegramChatId: text(),
	timezone: text().default('UTC').notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("users_email_key").using("btree", table.email.asc().nullsLast().op("text_ops")),
]);

export const accounts = pgTable("accounts", {
	id: text().primaryKey().notNull(),
	userId: text().notNull(),
	type: text().notNull(),
	provider: text().notNull(),
	providerAccountId: text().notNull(),
	refreshToken: text("refresh_token"),
	accessToken: text("access_token"),
	expiresAt: integer("expires_at"),
	tokenType: text("token_type"),
	scope: text(),
	idToken: text("id_token"),
	sessionState: text("session_state"),
}, (table) => [
	uniqueIndex("accounts_provider_providerAccountId_key").using("btree", table.provider.asc().nullsLast().op("text_ops"), table.providerAccountId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "accounts_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);
