// SpiderNode schema — the single Drizzle schema authority (D-07).
//
// PROVENANCE (DRZ-01): originally generated by `drizzle-kit pull`
// (schemaFilter public) from a LIVE production snapshot restored into a
// throwaway container (03-03 Task 2), then hand-finished line-by-line
// against .snapshots/prod-schema-only.sql and docs/ARCHITECTURE-AUDIT.md
// §11. NEVER derived from prisma/schema.prisma (frozen, D-09) — the live DDL
// is the only source of truth for pre-existing objects (M-6 drift rule).
//
// RECONCILED to the fully-migrated shape (03-07): migration 0001
// (03-04) added every audit §11 worker prerequisite — monitors claim column
// (next_check_at, timestamptz + due index) and consecutive_failures,
// write_guards, outbox (+unsent index), pings.error_class/status_code, the
// one-ongoing partial unique index, and gen_random_uuid()::text defaults on
// the text PKs. This file is now a pull of the docker test database after
// the full committed migration set (0000 + 0001) ran through the single
// runner — the state src/db/schema.ts must always describe. The two
// non-verbatim adaptations: (1) pull renders the gen_random_uuid() defaults
// as `.default((gen_random_uuid()))`, a bare call to an identifier
// drizzle-orm does not export; they are kept here in the canonical
// `.default(sql`gen_random_uuid()`)` form. (2) pull renders the opclass of
// the BOOLEAN isActive column in idx_monitors_due as `timestamptz_ops`
// (a serializer quirk on that two-column btree — PostgreSQL cannot create
// that pairing, error 42804, and `drizzle-kit generate` would emit it
// invalidly); it is kept here as the correct `bool_ops`. The 03-07 gate's
// normalization applies both rewrites to BOTH sides of its diff before
// comparing.
//
// GATE CONTRACT (03-07, D-13): the code below keeps the exact formatting
// drizzle-kit pull emits (single quotes, no semicolons, pull's column and
// table ordering). The empty-diff gate diffs this file against a normalized
// pull of a migrated database — cosmetic reformatting here would break the
// gate. Only comments (stripped by the gate's normalization) may differ.
//
// Live-DDL facts recorded at pull time (03-03): source PostgreSQL 17 (local
// spidernode-dev-db container — no Neon involved); every pre-existing time
// column is `timestamp(3) without time zone` (A6 — naive, not timestamptz;
// 0001's new columns are timestamptz per §11); `_prisma_migrations` is
// ABSENT (A4 — schema was db-push'd, never migrate-deploy'd; the gate
// needs no tablesFilter exclusion).
import { pgTable, uniqueIndex, text, timestamp, foreignKey, index, serial, boolean, integer, doublePrecision, jsonb } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const users = pgTable("users", {
	id: text().default(sql`gen_random_uuid()`).primaryKey().notNull(),
	name: text(),
	email: text().notNull(),
	emailVerified: timestamp({ precision: 3, mode: 'string' }),
	image: text(),
	password: text(),
	telegramChatId: text(),
	timezone: text().default('UTC').notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("users_email_key").using("btree", table.email.asc().nullsLast().op("text_ops")),
]);

export const sessions = pgTable("sessions", {
	id: text().primaryKey().notNull(),
	sessionToken: text().notNull(),
	userId: text().notNull(),
	expires: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("sessions_sessionToken_key").using("btree", table.sessionToken.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "sessions_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const writeGuards = pgTable("write_guards", {
	key: text().primaryKey().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const monitors = pgTable("monitors", {
	id: serial().primaryKey().notNull(),
	url: text().notNull(),
	name: text().notNull(),
	status: text().default('UNKNOWN').notNull(),
	isActive: boolean().default(true).notNull(),
	interval: integer().default(5).notNull(),
	lastChecked: timestamp({ precision: 3, mode: 'string' }),
	responseTime: integer().default(0),
	uptimePercent: doublePrecision().default(100).notNull(),
	totalChecks: integer().default(0).notNull(),
	failedChecks: integer().default(0).notNull(),
	userId: text().notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp({ precision: 3, mode: 'string' }).notNull(),
	nextCheckAt: timestamp("next_check_at", { withTimezone: true, mode: 'string' }),
	consecutiveFailures: integer("consecutive_failures").default(0).notNull(),
}, (table) => [
	index("idx_monitors_due").using("btree", table.isActive.asc().nullsLast().op("bool_ops"), table.nextCheckAt.asc().nullsLast().op("timestamptz_ops")).where(sql`"isActive"`),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "monitors_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const pings = pgTable("pings", {
	id: text().default(sql`gen_random_uuid()`).primaryKey().notNull(),
	monitorId: integer().notNull(),
	status: text().notNull(),
	responseTime: integer().notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	errorClass: text("error_class"),
	statusCode: integer("status_code"),
}, (table) => [
	index("pings_monitorId_idx").using("btree", table.monitorId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.monitorId],
			foreignColumns: [monitors.id],
			name: "pings_monitorId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const feedbacks = pgTable("feedbacks", {
	id: text().primaryKey().notNull(),
	userId: text().notNull(),
	type: text().notNull(),
	title: text().notNull(),
	description: text().notNull(),
	status: text().default('PENDING').notNull(),
	upvotes: integer().default(0).notNull(),
	createdAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	index("feedbacks_userId_idx").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "feedbacks_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const incidents = pgTable("incidents", {
	id: text().default(sql`gen_random_uuid()`).primaryKey().notNull(),
	monitorId: integer().notNull(),
	status: text().notNull(),
	description: text(),
	startedAt: timestamp({ precision: 3, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	resolvedAt: timestamp({ precision: 3, mode: 'string' }),
}, (table) => [
	index("incidents_monitorId_idx").using("btree", table.monitorId.asc().nullsLast().op("int4_ops")),
	uniqueIndex("incidents_one_ongoing").using("btree", table.monitorId.asc().nullsLast().op("int4_ops")).where(sql`(status = 'ONGOING'::text)`),
	foreignKey({
			columns: [table.monitorId],
			foreignColumns: [monitors.id],
			name: "incidents_monitorId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const verificationTokens = pgTable("verification_tokens", {
	id: text().primaryKey().notNull(),
	email: text().notNull(),
	token: text().notNull(),
	expires: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("verification_tokens_email_token_key").using("btree", table.email.asc().nullsLast().op("text_ops"), table.token.asc().nullsLast().op("text_ops")),
	uniqueIndex("verification_tokens_token_key").using("btree", table.token.asc().nullsLast().op("text_ops")),
]);

export const accounts = pgTable("accounts", {
	id: text().primaryKey().notNull(),
	userId: text().notNull(),
	type: text().notNull(),
	provider: text().notNull(),
	providerAccountId: text().notNull(),
	refreshToken: text("refresh_token"),
	accessToken: text("access_token"),
	expiresAt: integer("expires_at"),
	tokenType: text("token_type"),
	scope: text(),
	idToken: text("id_token"),
	sessionState: text("session_state"),
}, (table) => [
	uniqueIndex("accounts_provider_providerAccountId_key").using("btree", table.provider.asc().nullsLast().op("text_ops"), table.providerAccountId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "accounts_userId_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);

export const passwordResetTokens = pgTable("password_reset_tokens", {
	id: text().primaryKey().notNull(),
	email: text().notNull(),
	token: text().notNull(),
	expires: timestamp({ precision: 3, mode: 'string' }).notNull(),
}, (table) => [
	uniqueIndex("password_reset_tokens_email_token_key").using("btree", table.email.asc().nullsLast().op("text_ops"), table.token.asc().nullsLast().op("text_ops")),
	uniqueIndex("password_reset_tokens_token_key").using("btree", table.token.asc().nullsLast().op("text_ops")),
]);

export const outbox = pgTable("outbox", {
	id: text().default(sql`gen_random_uuid()`).primaryKey().notNull(),
	eventType: text("event_type").notNull(),
	monitorId: integer("monitor_id").notNull(),
	incidentId: text("incident_id"),
	payload: jsonb().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'string' }),
	attempts: integer().default(0).notNull(),
}, (table) => [
	index("idx_outbox_unsent").using("btree", table.createdAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(sent_at IS NULL)`),
	foreignKey({
			columns: [table.monitorId],
			foreignColumns: [monitors.id],
			name: "outbox_monitor_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.incidentId],
			foreignColumns: [incidents.id],
			name: "outbox_incident_id_fkey"
		}).onDelete("cascade"),
]);
