#!/usr/bin/env node
// schema-gate.mjs — the two schema-ownership gates behind `pnpm schema:gate`
// (03-07, D-13): DRZ-03's empty-diff gate + DRZ-02's "no longer exists
// anywhere" absence scan. Plain Node ESM, zero new deps. Run from the repo
// root; fails loud on every error path.
//
// Gate 1 — the empty-diff gate (T-03-17/T-03-19):
//   a. `drizzle-kit migrate` against the guarded docker TEST database —
//      idempotent: inside `pnpm verify` the DB is already migrated by the
//      vitest global-setup, so this is a no-op re-check; a standalone gate
//      run gets the same "introspection target is current" guarantee.
//   b. `drizzle-kit pull --config=drizzle.gate.config.ts` → ./.tmp-gate/schema.ts
//      (schemaFilter ["public"] — Pitfall 4: the runner's own bookkeeping
//      schema must never pollute the pull).
//   c. Normalized STRUCTURAL diff of the pull against the committed
//      src/db/schema.ts. BOTH sides are normalized identically (line endings,
//      // comments outside string literals, trailing whitespace, blank lines,
//      expression-default + boolean-opclass canonicalization), then compared
//      STRUCTURALLY:
//      imports as a sorted set, each `export const` block by name with its
//      internal lines ordered (pull's TOP-LEVEL ordering is not stable
//      run-to-run — see parseBlocks). The committed schema is pull-generated
//      (03-03 discipline), so post-normalization structural equality is the
//      steady state. ANY drift prints it and exits 1 — silent drift must fail
//      the operator's single typed gate command before it can ship.
//
// Gate 2 — the destructive-push absence scan (T-03-18), runs only after the
//   diff half passes: the retired destructive prisma push command form and
//   its data-loss flag must not exist in any executable surface —
//   package.json, src/, tests/, .github/, scripts/ — EXCLUDING this file
//   itself (it must not match its own scanner). The two search literals are
//   built from concatenated fragments so this scanning file never contains
//   them verbatim. docs/ is deliberately out of scope: the deploy runbook
//   narrates the command's historical deletion and must not trip an
//   executable-surface gate.
//
// ./.tmp-gate is deleted at the start of every pull AND in a finally block —
// it never survives a run, success or failure. Per-step wall times are
// printed on green (the Pitfall 9 budget evidence).

import { execSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import path from "node:path";

const GATE_OUT_DIR = ".tmp-gate";
const GATE_CONFIG = "drizzle.gate.config.ts";
const COMMITTED_SCHEMA = path.join("src", "db", "schema.ts");
const SELF_PATH = path.resolve("scripts", "schema-gate.mjs");
// Mirrors vitest.config.ts: the docker-compose.test.yml test database
// (Postgres :5453, offset from the common local default — see
// docker-compose.test.yml for the sibling-stack rationale).
const DEFAULT_TEST_DATABASE_URL =
  "postgresql://postgres:postgres@localhost:5453/uptime_test";
const SCAN_DIR_ROOTS = ["src", "tests", ".github", "scripts"];
const SCAN_SINGLE_FILES = ["package.json"];
const SCAN_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".json",
  ".yml",
  ".yaml",
  ".sh",
]);
// Generated output is not an editable executable surface (the prisma client
// is regenerated by every build and would drown the scan). gsd-core (07-08
// Rule-3 unblock) is the vendored GSD tooling bundle left untracked under
// .github/ by the agent harness — its docs/registry .cjs prose quotes the
// retired push command form as documentation, not as this repo's executable
// surface. Same posture as the generated/ skip: tool-owned content.
const SCAN_SKIP_DIR_NAMES = new Set(["node_modules", "generated", ".tmp-gate", "gsd-core"]);
const MAX_DIFF_LINES_SHOWN = 80;

function fail(context, error) {
  throw new Error(
    `schema-gate failed: ${context}. ` +
      `Cause: ${error instanceof Error ? error.message : String(error)}.`
  );
}

function ms(milliseconds) {
  return `${(milliseconds / 1000).toFixed(2)}s`;
}

// Resolve the docker TEST database URL exactly like vitest.config.ts:
// .env.test override-first when present, else this canonical
// localhost-docker constant. Ambient DATABASE_URL / .env are deliberately
// NOT consulted — the gate always targets the test stack, never a dev or
// production database.
function resolveTestDatabaseUrl() {
  if (existsSync(".env.test")) {
    for (const line of readFileSync(".env.test", "utf8").split(/\r?\n/)) {
      const match = line.match(
        /^\s*(?:export\s+)?(TEST_DATABASE_URL)\s*=\s*(.*)$/
      );
      if (!match) continue;
      let value = match[2].trim();
      const quoted = value.match(/^(['"])(.*)\1$/);
      if (quoted) value = quoted[2];
      process.env.TEST_DATABASE_URL = value;
    }
  }
  return process.env.TEST_DATABASE_URL ?? DEFAULT_TEST_DATABASE_URL;
}

// T-02-05 test-database safety guard, same rules as
// tests/setup/global-setup.ts: accept exactly localhost, 127.0.0.1 and
// *.docker.internal; refuse everything else and fail closed on unparseable
// URLs. The migrate step below can write — it must never leave localhost.
function assertLocalDatabaseUrl(url) {
  let hostname = null;
  try {
    hostname = new URL(url).hostname;
  } catch {
    hostname = null;
  }
  const isLocal =
    hostname === "localhost" ||
    hostname === "127.0.0.1" ||
    /^[a-z0-9-]+\.docker\.internal$/i.test(hostname ?? "");
  if (!hostname || !isLocal) {
    const shown = hostname ?? "(unparseable URL)";
    throw new Error(
      `Refusing to run the schema gate against non-local database host: ${shown}. ` +
        `Point TEST_DATABASE_URL at the docker test stack ` +
        `(docker-compose.test.yml) and try again.`
    );
  }
}

// Strip a `//` line comment, but only OUTSIDE string/template literals — a
// naive regex would truncate on `//` inside a string value. Handles 'single',
// "double" and `template` quoting plus escaped characters; per-line state is
// independent, which is deterministic-identical on both diffed files.
function stripLineComment(line) {
  let result = "";
  let quote = null;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (quote) {
      result += char;
      if (char === "\\" && i + 1 < line.length) {
        result += line[i + 1];
        i++;
      } else if (char === quote) {
        quote = null;
      }
      continue;
    }
    if (char === "'" || char === '"' || char === "`") {
      quote = char;
      result += char;
      continue;
    }
    if (char === "/" && line[i + 1] === "/") break;
    result += char;
  }
  return result;
}

// Canonicalize pull's rendering of argument-less expression defaults.
// drizzle-kit pull (0.31.x pg serializer) renders a `(gen_random_uuid())::text`
// column default as `.default((gen_random_uuid()))` — a bare call to an
// identifier drizzle-orm does NOT export (verified against pg-core's runtime
// exports), so that line is not adoptable TypeScript. The canonical drizzle
// idiom for the same default is `.default(sql`gen_random_uuid()`)`. This rule
// rewrites BOTH sides into the canonical form, preserving the function
// identity: a genuinely changed default still drifts (fail-closed), only the
// rendering is unified. Argument-less calls only — anything weirder is left
// untouched and fails the gate red for a human to look at (T-03-19 posture:
// false-positives erode trust, false-negatives-to-red are safe).
function canonicalizeDefaultRenderings(line) {
  return line.replace(
    /\.default\(\(([A-Za-z_][A-Za-z0-9_]*)\(\)\)\)/g,
    ".default(sql`$1()`)"
  );
}

// Canonicalize the opclass pull renders on a BOOLEAN index column (WR-01).
// drizzle-kit pull (0.31.x pg serializer) renders `timestamptz_ops` on BOTH
// columns of idx_monitors_due (boolean "isActive" + timestamptz
// next_check_at) even though the live index carries default opclasses
// (migration 0001 created it without any) and PostgreSQL rejects a
// timestamptz opclass on a boolean outright (error 42804). The committed
// schema authority therefore spells `bool_ops` — the opclass generate must
// be able to round-trip — and this rule rewrites pull's quirk to the same
// rendering, identically on BOTH sides. Fail-closed posture is preserved:
// an opclass change on any NON-boolean column still drifts, and a boolean
// column outside this set still drifts on any opclass difference. Extend
// the set when a future boolean column joins an index.
const BOOLEAN_INDEXED_COLUMNS = new Set(["isActive"]);
function canonicalizeBooleanOpclass(line) {
  return line.replace(
    /(table\.([A-Za-z_][A-Za-z0-9_]*)\.(?:asc|desc)\(\)\.nulls(?:First|Last)\(\)\.op\(")([A-Za-z0-9_]+)(_ops"\))/g,
    (match, prefix, columnName, opclass, suffix) =>
      BOOLEAN_INDEXED_COLUMNS.has(columnName) && opclass !== "bool"
        ? `${prefix}bool${suffix}`
        : match
  );
}

// Canonicalize pull's property rendering of the users.email_verified boolean
// column (07-01). pull camelCases every column name into the property, so the
// physical column "email_verified" renders as the property `emailVerified` —
// which ALREADY exists on the users table (the legacy timestamp; D-30 forbids
// touching it). Adopting pull's line verbatim would put two `emailVerified:`
// properties in one object literal — TS1117 under this repo's strict tsconfig
// (the same "not adoptable TypeScript" class the gen_random_uuid rule above
// exists for), so the committed authority spells the property `email_verified`
// (matching the physical column) and this rule rewrites pull's rendering into
// that canonical form on BOTH sides, identically. Fail-closed posture holds:
// only this exact column name + type is rewritten; any other drift in the
// block (type change, default change, a THIRD emailVerified column) still
// diffs red.
function canonicalizeEmailVerifiedCollision(line) {
  return line.replace(
    /^(\s*)emailVerified:( boolean\("email_verified"\).*)$/,
    "$1email_verified:$2"
  );
}

// Canonicalize pull's property rendering of the windowed uptime columns
// (08-01, DAT-11). drizzle-kit pull camelCases every column name into the
// property via its bundled camelcase@7, which UPPERCASES the letter following
// a digit: physical "uptime24h"/"uptime7d"/"uptime30d" render as properties
// uptime24H/uptime7D/uptime30D with NO explicit column-name argument —
// adopting pull's line verbatim would describe physical columns that do not
// exist (the same non-adoptable-rendering class as the gen_random_uuid
// default above). The committed authority spells the property with the
// physical column name (the drizzle property IS the column name when no
// explicit name is given), and this rule rewrites pull's rendering into that
// canonical form on BOTH sides, identically. Fail-closed posture holds: only
// these three exact renderings are rewritten; any other drift in the block
// (type change, default change, a renamed window column) still diffs red.
function canonicalizeUptimeWindowProperties(line) {
  return line
    .replace(/^(\s*)uptime24H:( doublePrecision\(\),?)$/, "$1uptime24h:$2")
    .replace(/^(\s*)uptime7D:( doublePrecision\(\),?)$/, "$1uptime7d:$2")
    .replace(/^(\s*)uptime30D:( doublePrecision\(\),?)$/, "$1uptime30d:$2");
}

// The documented normalization (03-07 Task 1, research A5 — textual route):
// identical on BOTH sides — strip // comments, trim trailing whitespace,
// drop blank lines (collapsing runs), normalize line endings (the Windows
// checkout reality), and canonicalize expression-default + boolean-opclass
// renderings (above). Only after this transform are the pull output and the
// committed schema expected to be equal.
function normalizeSchema(text) {
  const lines = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = canonicalizeUptimeWindowProperties(
      canonicalizeEmailVerifiedCollision(
        canonicalizeBooleanOpclass(
          canonicalizeDefaultRenderings(
            stripLineComment(rawLine).replace(/\s+$/, "")
          )
        )
      )
    );
    if (line.trim() === "") continue;
    lines.push(line);
  }
  return lines;
}

// Classic LCS line diff (`-` committed schema only, `+` migrated database
// only). Both sides are a few hundred lines — the O(n*m) table is trivial.
function diffLines(a, b) {
  const n = a.length;
  const m = b.length;
  const dp = Array.from({ length: n + 1 }, () => new Int32Array(m + 1));
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      dp[i][j] =
        a[i] === b[j]
          ? dp[i + 1][j + 1] + 1
          : Math.max(dp[i + 1][j], dp[i][j + 1]);
    }
  }
  const ops = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i] === b[j]) {
      ops.push({ type: " ", line: a[i] });
      i++;
      j++;
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      ops.push({ type: "-", line: a[i] });
      i++;
    } else {
      ops.push({ type: "+", line: b[j] });
      j++;
    }
  }
  while (i < n) ops.push({ type: "-", line: a[i++] });
  while (j < m) ops.push({ type: "+", line: b[j++] });
  return ops;
}

// STRUCTURAL comparison (the research A5 / Open Question 2 spike, exercised):
// drizzle-kit pull's TOP-LEVEL ordering is NOT stable run-to-run — the import
// list order and the table statement order vary with database catalog state
// (Postgres returns catalog rows in an order that TRUNCATE/seed activity
// perturbs, and the serializer follows it). Comparing raw line order would
// false-positive the gate after every `pnpm test`. Instead, both sides are
// parsed into structure:
//   - import lines  → compared as a SORTED SET (order is meaningless)
//   - each `export const <name> = ...` block (pgTable/pgEnum/...) → compared
//     BY NAME as an unordered map, with the block's INTERNAL lines still in
//     order (column/index drift inside one table is still caught — column
//     order is the DB's stable ordinal position)
// Any top-level line that is neither an import nor an export block is keyed
// by its own content, so it can never silently vanish from the comparison.
// Canonicalize an import line's SPECIFIER ORDER: `import { b, a } from "x"`
// and `import { a, b } from "x"` are the same statement. drizzle-kit pull
// emits the pg-core specifiers in serializer-visit order, which is not stable
// run-to-run (see parseBlocks) — sorting the names on BOTH sides removes that
// false positive while still catching a genuinely added/removed/renamed
// import (the sorted sets then differ).
function canonicalizeImportLine(line) {
  const match = line.match(/^import \{(.*)\} from (.+)$/);
  if (!match) return line;
  const specifiers = match[1]
    .split(",")
    .map((specifier) => specifier.trim())
    .filter((specifier) => specifier !== "")
    .sort();
  return `import { ${specifiers.join(", ")} } from ${match[2]}`;
}

function parseBlocks(lines) {
  const imports = new Set();
  const blocks = new Map();
  let current = null;
  for (const line of lines) {
    if (current) {
      current.lines.push(line);
      // `]);` (pgTable), `});` (single-line-close pgTable/pgEnum object) or
      // `);` (bare call) — each terminator char individually escaped; a
      // block's internal lines always end with `,` or `{`, never these
      if (/^\]\);$|^\}\);$|^\);$/.test(line.trim())) {
        blocks.set(current.name, current.lines);
        current = null;
      }
      continue;
    }
    if (line.startsWith("import ")) {
      imports.add(canonicalizeImportLine(line));
      continue;
    }
    const match = line.match(/^export const ([A-Za-z_][A-Za-z0-9_]*) = /);
    if (match) {
      current = { name: match[1], lines: [line] };
      continue;
    }
    blocks.set(`(top-level) ${line}`, [line]);
  }
  if (current) {
    throw new Error(
      `schema-gate failed: unterminated export block in schema source ` +
        `(started at "${current.lines[0]}").`
    );
  }
  return { imports, blocks };
}

function compareStructures(committedLines, pulledLines) {
  const committed = parseBlocks(committedLines);
  const pulled = parseBlocks(pulledLines);
  const problems = [];

  const committedImports = [...committed.imports].sort();
  const pulledImports = [...pulled.imports].sort();
  const importOps = diffLines(committedImports, pulledImports);
  if (importOps.some((op) => op.type !== " ")) {
    problems.push({ scope: "imports", ops: importOps });
  }

  for (const name of [...committed.blocks.keys()]) {
    if (!pulled.blocks.has(name)) {
      problems.push({
        scope: name,
        ops: [
          {
            type: "-",
            line: `${name} exists only in the committed src/db/schema.ts (missing from the migrated database)`,
          },
        ],
      });
    }
  }
  for (const name of [...pulled.blocks.keys()]) {
    if (!committed.blocks.has(name)) {
      problems.push({
        scope: name,
        ops: [
          {
            type: "+",
            line: `${name} exists only in the migrated database (missing from committed src/db/schema.ts)`,
          },
        ],
      });
    }
  }
  for (const [name, lines] of committed.blocks) {
    const other = pulled.blocks.get(name);
    if (!other) continue;
    const ops = diffLines(lines, other);
    if (ops.some((op) => op.type !== " ")) {
      problems.push({ scope: name, ops });
    }
  }
  return problems;
}

function printDrift(problems) {
  const totalDiffering = problems.reduce(
    (sum, problem) => sum + problem.ops.filter((op) => op.type !== " ").length,
    0
  );
  console.error(
    `[schema-gate] DRIFT: src/db/schema.ts does not match the migrated ` +
      `database — ${problems.length} problem area(s), ${totalDiffering} ` +
      `differing line(s). (- committed schema only · + migrated database only)`
  );
  let shown = 0;
  for (const problem of problems) {
    if (shown >= MAX_DIFF_LINES_SHOWN) {
      console.error(
        `  ... output truncated at ${MAX_DIFF_LINES_SHOWN} lines ` +
          `(remaining problem areas: ${problems
            .slice(problems.indexOf(problem))
            .map((p) => p.scope)
            .join(", ")})`
      );
      break;
    }
    console.error(`  [${problem.scope}]`);
    for (const op of problem.ops) {
      if (op.type === " ") continue;
      if (shown >= MAX_DIFF_LINES_SHOWN) break;
      console.error(`  ${op.type} ${op.line}`);
      shown++;
    }
  }
  console.error(
    `Fix direction: schema changes belong in a NEW drizzle migration ` +
      `(drizzle-kit generate), with src/db/schema.ts regenerated from the ` +
      `migrated database (drizzle-kit pull). Never hand-edit one side alone.`
  );
}

// The two forbidden search literals, assembled from concatenated fragments so
// THIS file never contains them verbatim (T-03-18: the retired destructive
// command must not be copy-pasteable out of the gate script itself).
const FORBIDDEN_LITERALS = [
  { label: "retired destructive push command form", literal: ["prisma", " d", "b ", "push"].join("") },
  { label: "destructive data-loss flag", literal: ["--acce", "pt-da", "ta-l", "oss"].join("") },
];

function collectScannableFiles(root, files) {
  if (!existsSync(root)) return; // e.g. .github/ does not exist in this repo era
  const stats = statSync(root);
  if (stats.isDirectory()) {
    if (SCAN_SKIP_DIR_NAMES.has(path.basename(root))) return;
    for (const entry of readdirSync(root)) {
      collectScannableFiles(path.join(root, entry), files);
    }
  } else if (SCAN_EXTENSIONS.has(path.extname(root))) {
    files.push(root);
  }
}

function scanForbiddenTokens() {
  const files = [...SCAN_SINGLE_FILES];
  for (const root of SCAN_DIR_ROOTS) collectScannableFiles(root, files);

  const hits = [];
  for (const file of files) {
    // Self-exclusion: the scanner must not match its own fragment-built code.
    if (path.resolve(file) === SELF_PATH) continue;
    const lines = readFileSync(file, "utf8").split(/\r?\n/);
    lines.forEach((line, index) => {
      for (const forbidden of FORBIDDEN_LITERALS) {
        if (line.includes(forbidden.literal)) {
          hits.push({ file, line: index + 1, label: forbidden.label, text: line });
        }
      }
    });
  }
  return hits;
}

function main() {
  if (!existsSync(GATE_CONFIG) || !existsSync(COMMITTED_SCHEMA)) {
    throw new Error(
      "schema-gate failed: run from the repository root " +
        `(expected ${GATE_CONFIG} and ${COMMITTED_SCHEMA} in the cwd).`
    );
  }

  const url = resolveTestDatabaseUrl();
  assertLocalDatabaseUrl(url);
  // What the drizzle-kit subprocesses read (drizzle.gate.config.ts throws
  // when it is missing — never logged anywhere).
  process.env.DATABASE_URL = url;

  const timings = {};
  try {
    // (a) idempotent migrate — the introspection target is always current
    let stepStart = Date.now();
    try {
      execSync("pnpm exec drizzle-kit migrate", { stdio: "inherit" });
    } catch (error) {
      fail(
        "drizzle-kit migrate could not prepare the test database " +
          "(likely: the docker test stack is down — docker compose -f " +
          "docker-compose.test.yml up -d --wait — or a migration file broke)",
        error
      );
    }
    timings.migrate = Date.now() - stepStart;

    // (b) pull into the throwaway folder (stale output from a killed run
    // can never leak into this diff)
    rmSync(GATE_OUT_DIR, { recursive: true, force: true });
    stepStart = Date.now();
    try {
      execSync(`pnpm exec drizzle-kit pull --config=${GATE_CONFIG}`, {
        stdio: "inherit",
      });
    } catch (error) {
      fail("drizzle-kit pull (gate config)", error);
    }
    timings.pull = Date.now() - stepStart;
    const pulledSchemaPath = path.join(GATE_OUT_DIR, "schema.ts");
    if (!existsSync(pulledSchemaPath)) {
      throw new Error(
        `schema-gate failed: ${pulledSchemaPath} was not produced by the pull.`
      );
    }

    // (c) normalized STRUCTURAL diff against the committed schema (top-level
    // order-insensitive — see parseBlocks for why raw line order is unstable)
    stepStart = Date.now();
    const committed = normalizeSchema(readFileSync(COMMITTED_SCHEMA, "utf8"));
    const pulled = normalizeSchema(readFileSync(pulledSchemaPath, "utf8"));
    const problems = compareStructures(committed, pulled);
    timings.diff = Date.now() - stepStart;
    if (problems.length > 0) {
      printDrift(problems);
      process.exitCode = 1;
      return; // scan half fires only after the diff half passes
    }

    // (e) the destructive-push absence scan
    stepStart = Date.now();
    const hits = scanForbiddenTokens();
    timings.scan = Date.now() - stepStart;
    if (hits.length > 0) {
      console.error(
        `[schema-gate] FORBIDDEN TOKENS: ${hits.length} hit(s) in executable surfaces ` +
          `(the retired destructive push path must not exist anywhere — DRZ-02):`
      );
      for (const hit of hits) {
        console.error(`  ${hit.file}:${hit.line}: ${hit.label}`);
        console.error(`    > ${hit.text.trim()}`);
      }
      process.exitCode = 1;
      return;
    }

    console.log(
      `[schema-gate] green — empty diff, no forbidden tokens ` +
        `(migrate ${ms(timings.migrate)} · pull ${ms(timings.pull)} · ` +
        `diff ${ms(timings.diff)} · scan ${ms(timings.scan)})`
    );
  } finally {
    // (f) the throwaway folder never survives a run — success or failure
    rmSync(GATE_OUT_DIR, { recursive: true, force: true });
  }
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
